"use client"

import React, { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer"; 
import GoTop from "@/app/components/GoTop";
import PlantNav from "@/app/components/PlantNav";
import DropItem from "@/app/components/DropItem";

import ava1 from "@/assets/img/ava1.svg";
import ava2 from "@/assets/img/ava2.svg";
import lavender from "@/assets/plants/lavender.png";
import PopularPlant from "@/app/components/PopularPlant";
import ShareIt from "@/app/components/ShareIt";


export default function Detail() {
  const [open, setOpen] = useState(false);
  
  const toggle = (index) => {
    if (open === index) {
      return setOpen(null);
    }

    setOpen(index);
  };

  const accordionData = [
    {
        title: "What are some ways to enjoy the flavors of lavender?",
        desc: "Use dried lavender flowers for seasoning desserts, such as cookies, cakes, and ice cream, or as an edible garnish. Lavender blends deliciously with mint and lemon to brew a refreshing tea. Or try blending your own Herbes de Provence mix by combining dried lavender blooms with thyme, basil, fennel, and savory. Use this blend to season grilled meats and other savory dishes."
    },
    {
        title: "What's the best way to dry lavender?",
        desc: "Cut stems just before they reach peak bloom, snipping them as long as possible. Remove the lower leaves along each stem, bundle 4-6 stems together with a string or rubber band, and hang upside down in a dark, well-ventilated area until dry. To dry just the lavender flowers, remove them from the stem and place them on a flat surface in a dark, dry location."
    },
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />
      <ShareIt />

      <div className="flex flex-col bg-white min-h-screen relative2">
        <div className="bg-[#f8f3e7] py-5 mb-0">
          <h1 className="relative mx-3 md:mx-auto text-gray-900 text-3xl md:text-5xl md:leading-[60px] max-w-3xl m-auto font-semibold text-center mt-4 sm:mt-6 mb-5 sm:mb-0">
          How to Plant and Grow Lavender
          </h1>

          <a href="" className="flex items-center justify-center sm:hidden">
            <div>
              <div className="border-white rounded-full border-3 w-10 h-10 roundedShadow">
                <span
                  style={{
                    boxSizing: "border-box",
                    display: "inline-block",
                    overflow: "hidden",
                    width: "initial",
                    height: "initial",
                    background: "none",
                    opacity: 1,
                    border: "0px",
                    margin: "0px",
                    padding: "0px",
                    position: "relative",
                    maxWidth: "100%",
                  }}
                >
                  <span
                    style={{
                      boxSizing: "border-box",
                      display: "block",
                      width: "initial",
                      height: "initial",
                      background: "none",
                      opacity: 1,
                      border: "0px",
                      margin: "0px",
                      padding: "0px",
                      maxWidth: "100%",
                    }}
                  >
                    <Image
                      alt=""
                      aria-hidden="true"
                      src={ava1}
                      className="rounded-full "
                      style={{
                        display: "block",
                        maxWidth: "100%",
                        width: "initial",
                        height: "initial",
                        background: "none",
                        opacity: 1,
                        border: "0px",
                        margin: "0px",
                        padding: "0px",
                      }}
                    />
                  </span>
                </span>
              </div>
            </div>
            <p className="text-sm font-semibold text-[#404040] ml-2">
              Annanya Chaturvedi
            </p>
          </a>
          <div className="mt-4 sm:mt-6 text-center text-[#565656] flex justify-center items-center sm:divide-x relative sm:space-x-3 divide-[#CACACA]">
            <a
              href=""
              className="items-center justify-center hidden font-medium sm:flex"
            >
              <div>
                <div className="border-white rounded-full border-3 hidden text-[20px] leading-9 text-center w-11 h-11 left-11 -top-6 roundedShadow sm:block">
                  <span
                    style={{
                      boxSizing: "border-box",
                      display: "inline-block",
                      overflow: "hidden",
                      width: "initial",
                      height: "initial",
                      background: "none",
                      opacity: 1,
                      border: "0px",
                      margin: "0px",
                      padding: "0px",
                      position: "relative",
                      maxWidth: "100%",
                    }}
                  >
                    <span
                      style={{
                        boxSizing: "border-box",
                        display: "block",
                        width: "initial",
                        height: "initial",
                        background: "none",
                        opacity: 1,
                        border: "0px",
                        margin: "0px",
                        padding: "0px",
                        maxWidth: "100%",
                      }}
                    >
                      <Image
                        alt=""
                        aria-hidden="true"
                        src={ava1}
                        className="rounded-full "
                        style={{
                          display: "block",
                          maxWidth: "100%",
                          width: "initial",
                          height: "initial",
                          background: "none",
                          opacity: 1,
                          border: "0px",
                          margin: "0px",
                          padding: "0px",
                        }}
                      />
                    </span>
                  </span>
                </div>
              </div>
              <p className="text-sm font-semibold text-[#404040] sm:ml-5 hidden sm:block">
                Annanya Chaturvedi
              </p>
            </a>
            <div className="flex items-center pl-0 sm:pl-3 border-r pr-3 sm:pr-0 border-[#CACACA]">
              <svg
                width="16"
                height="16"
                viewBox="0 0 16 16"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <g clip-path="url(#clip0_238_253)">
                  <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M6.08333 0.666626C6.08333 0.252412 5.74754 -0.083374 5.33333 -0.083374C4.91912 -0.083374 4.58333 0.252412 4.58333 0.666626V1.1679C2.39564 2.1441 0.827616 4.24638 0.609016 6.74499C0.5833 7.03892 0.583311 7.37848 0.583329 7.95321L0.58333 7.99996L0.583329 8.04671C0.583311 8.62144 0.5833 8.961 0.609016 9.25493C0.894515 12.5182 3.48176 15.1054 6.74503 15.3909C7.03896 15.4167 7.37853 15.4166 7.95327 15.4166L8 15.4166L8.04673 15.4166C8.62147 15.4166 8.96103 15.4167 9.25497 15.3909C12.5182 15.1054 15.1055 12.5182 15.391 9.25493C15.4167 8.96099 15.4167 8.62143 15.4167 8.04669V7.99996V7.95323C15.4167 7.37849 15.4167 7.03892 15.391 6.74499C15.1724 4.24638 13.6043 2.1441 11.4167 1.1679V0.666626C11.4167 0.252412 11.0809 -0.083374 10.6667 -0.083374C10.2524 -0.083374 9.91666 0.252412 9.91666 0.666626V0.69974C9.69963 0.658998 9.47889 0.628569 9.25497 0.608979C8.96104 0.583263 8.62148 0.583274 8.04675 0.583292L8 0.583293L7.95325 0.583292C7.37852 0.583274 7.03896 0.583263 6.74503 0.608979C6.5211 0.628569 6.30036 0.658998 6.08333 0.69974V0.666626ZM9.91666 2.66663V2.23383C9.65952 2.17098 9.39487 2.12695 9.12423 2.10327C8.90411 2.08401 8.63494 2.08329 8 2.08329C7.36505 2.08329 7.09589 2.08401 6.87576 2.10327C6.60513 2.12695 6.34047 2.17098 6.08333 2.23383V2.66663C6.08333 3.08084 5.74754 3.41663 5.33333 3.41663C4.98139 3.41663 4.68606 3.17421 4.60522 2.84725C3.21603 3.69303 2.25298 5.16494 2.10331 6.87572C2.08405 7.09585 2.08333 7.36502 2.08333 7.99996C2.08333 8.6349 2.08405 8.90407 2.10331 9.12419C2.32536 11.6623 4.33767 13.6746 6.87576 13.8966C7.09589 13.9159 7.36505 13.9166 8 13.9166C8.63494 13.9166 8.90411 13.9159 9.12423 13.8966C11.6623 13.6746 13.6746 11.6623 13.8967 9.12419C13.9159 8.90407 13.9167 8.6349 13.9167 7.99996C13.9167 7.36502 13.9159 7.09585 13.8967 6.87572C13.747 5.16493 12.784 3.69303 11.3948 2.84724C11.3139 3.17421 11.0186 3.41663 10.6667 3.41663C10.2524 3.41663 9.91666 3.08084 9.91666 2.66663ZM4.66666 4.58329C4.25245 4.58329 3.91666 4.91908 3.91666 5.33329C3.91666 5.74751 4.25245 6.08329 4.66666 6.08329H11.3333C11.7475 6.08329 12.0833 5.74751 12.0833 5.33329C12.0833 4.91908 11.7475 4.58329 11.3333 4.58329H4.66666ZM6 8.66663C6 9.03481 5.70152 9.33329 5.33333 9.33329C4.96514 9.33329 4.66666 9.03481 4.66666 8.66663C4.66666 8.29844 4.96514 7.99996 5.33333 7.99996C5.70152 7.99996 6 8.29844 6 8.66663ZM5.33333 12C5.70152 12 6 11.7015 6 11.3333C6 10.9651 5.70152 10.6666 5.33333 10.6666C4.96514 10.6666 4.66666 10.9651 4.66666 11.3333C4.66666 11.7015 4.96514 12 5.33333 12ZM8.66666 11.3333C8.66666 11.7015 8.36819 12 8 12C7.63181 12 7.33333 11.7015 7.33333 11.3333C7.33333 10.9651 7.63181 10.6666 8 10.6666C8.36819 10.6666 8.66666 10.9651 8.66666 11.3333ZM10.6667 12C11.0349 12 11.3333 11.7015 11.3333 11.3333C11.3333 10.9651 11.0349 10.6666 10.6667 10.6666C10.2985 10.6666 10 10.9651 10 11.3333C10 11.7015 10.2985 12 10.6667 12ZM8.66666 8.66663C8.66666 9.03481 8.36819 9.33329 8 9.33329C7.63181 9.33329 7.33333 9.03481 7.33333 8.66663C7.33333 8.29844 7.63181 7.99996 8 7.99996C8.36819 7.99996 8.66666 8.29844 8.66666 8.66663ZM10.6667 9.33329C11.0349 9.33329 11.3333 9.03481 11.3333 8.66663C11.3333 8.29844 11.0349 7.99996 10.6667 7.99996C10.2985 7.99996 10 8.29844 10 8.66663C10 9.03481 10.2985 9.33329 10.6667 9.33329Z"
                    fill="#22272F"
                  ></path>
                </g>
                <defs>
                  <clipPath id="clip0_238_253">
                    <rect width="16" height="16" fill="white"></rect>
                  </clipPath>
                </defs>
              </svg>
              <p className="text-xs text-[#404040] leading-5 pl-2">
                12 June 2023
              </p>
            </div>
            <div className="flex items-center pl-3">
              <svg
                width="16"
                height="16"
                viewBox="0 0 16 16"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  fill-rule="evenodd"
                  clip-rule="evenodd"
                  d="M8.00001 0.583374C3.9039 0.583374 0.583344 3.90393 0.583344 8.00004C0.583344 12.0962 3.9039 15.4167 8.00001 15.4167C12.0961 15.4167 15.4167 12.0962 15.4167 8.00004C15.4167 3.90393 12.0961 0.583374 8.00001 0.583374ZM2.08334 8.00004C2.08334 4.73236 4.73233 2.08337 8.00001 2.08337C11.2677 2.08337 13.9167 4.73236 13.9167 8.00004C13.9167 11.2677 11.2677 13.9167 8.00001 13.9167C4.73233 13.9167 2.08334 11.2677 2.08334 8.00004ZM8.75001 5.33337C8.75001 4.91916 8.41422 4.58337 8.00001 4.58337C7.5858 4.58337 7.25001 4.91916 7.25001 5.33337V8.00004C7.25001 8.2508 7.37533 8.48498 7.58398 8.62408L9.58398 9.95741C9.92863 10.1872 10.3943 10.094 10.624 9.7494C10.8538 9.40475 10.7607 8.9391 10.416 8.70934L8.75001 7.59865V5.33337Z"
                  fill="#404040"
                ></path>
              </svg>
              <p className="text-xs text-[#404040] leading-5 pl-2">11 Mins</p>
            </div>
          </div>
        </div>
        <PlantNav />

        <div className="flex flex-row w-full">
          <div className="flex flex-1 flex-col items-center justify-center relative">
            <div className="flex flex-1 flex-col pb-18 max-w-md md:max-w-2xl ">
              <section className="w-full mx-auto  mt-0 md:mt-4 px-5 markdown-blog">
                {/* <div className="flex flex-col md:flex-row w-full items-center pb-4">
                  <nav className="w-full md:w-1/2  flex text-sm my-1 " aria-label="Breadcrumb">
                    <ol className="list-none p-0 inline-flex">
                      <li className="flex items-center">
                        <a
                          href="#"
                          className="uppercase text-gray-900 font-bold"
                        >
                          Gardening
                        </a>
                        <svg
                          className="fill-current text-gray-900 w-2 h-2 mx-1"
                          xmlns="http://www.w3.org/2000/svg"
                          viewBox="0 0 320 512"
                        >
                          <path d="M285.476 272.971L91.132 467.314c-9.373 9.373-24.569 9.373-33.941 0l-22.667-22.667c-9.357-9.357-9.375-24.522-.04-33.901L188.505 256 34.484 101.255c-9.335-9.379-9.317-24.544.04-33.901l22.667-22.667c9.373-9.373 24.569-9.373 33.941 0L285.475 239.03c9.373 9.372 9.373 24.568.001 33.941z" />
                        </svg>
                      </li>
                      <li>
                        <span className="text-gray-900 uppercase font-semibold">
                          lavender
                        </span>
                        
                      </li>
                      
                    </ol>
                  </nav>
                </div> */}

                <div>
                  <Image
                    src={lavender}
                    alt=""
                    className="w-full border object-cover shadow"
                  />
                </div>
                <article>
                  <p>
                  When you see photos of the famed lavender fields of Provence, France, it&lsquo;s love at first sight. A shrubby perennial native to the Mediterranean region, lavender might be the most enjoyable of all herbs. It appeals to almost every sense, with its calming scent, pungent taste, dainty flowers, and velvety gray-green leaves. Bonus points: It is deer-resistant and attracts butterflies and pollinators! Successfully growing lavender, however, depends on your type of garden soil, location, and climate.
                  </p>
                  <p>Note that not all lavender varieties are suitable for cooking; some lavenders are only grown for their ornamental value. It is usually the flowers of culinary lavender that are dried for cooking although some recipes from the South of France feature the fragrant leaves.</p>
                </article>

                <article>
                  <section name="where">
                    <div className="flex items-center space-x-2">
                      <span className="text-2xl font-semibold">
                      Where to Plant Lavender
                      </span>
                    </div>
                    <p>
                    When planting lavender, take your cues from the sun-drenched lavender fields in Provence and plant it in the sunniest spot possible, with excellent drainage. Lavender can put up with drought, heat, and wind but it does not do well in soggy soil. In its native habitat in the Mediterranean, lavender grows in rocky, slightly alkaline soils and performs best in a pH range of 6.5 to 8.2. The more your planting site mimics these conditions, the better the plant will do.
                    </p>
                    <p>
                    When designing a garden bed with lavender, keep in mind the mature growth of surrounding plants and give lavender a spot where other plants won’t cast any shade on it.
                    </p>
                  </section>

                  <section name="tips">
                    <div className="flex items-center space-x-2">
                      <span className="text-2xl font-semibold">
                      How and When to Plant Lavender
                      </span>
                    </div>
                    <p>
                    Give each lavender plenty of space to promote good air circulation. Spacing should be at least 18 to 24 inches depending on the variety. ‘Edelweiss’, for example, is one of the tallest lavenders that grows 2 feet tall, so it needs about the same spacing as its height. Especially in areas of high humidity, air circulation is key to keeping lavender plants happy.
                    </p>
                    <p>
                    Dig a hole that easily fits the diameter of the root ball. Lavender has shallow roots about 8 to 10 inches deep, so the planting hole does not need to be much deeper. Mulching around the plant is always a good idea to keep weeds out. Using gravel or black mulch also helps increase the heat around the roots.
                    </p>
                  </section>
                
                  <section name="care" className="">
                    <div className="flex items-center space-x-2">
                      <span className="text-2xl font-semibold">
                      Lavender Care Tips
                      </span>
                    </div>
                    <h3>
                        Light
                    </h3>
                    <p>
                    Always grow lavender in full sun, where it can receive at least 8-10 hours of direct sunlight per day.
                    </p>
                    <h3>
                    Soil and Water
                    </h3>
                    <p>
                    Lavender roots need many spaces between soil particles to breathe and grow, so this herb is well suited to sandy or rocky soil. If your garden has heavy clay soil that retains moisture, lavender roots simply rot and die. To create better soil structure, you can add plenty of organic material to the top 4 to 8 inches. Many commercial lavender growers use raised beds to improve drainage, a technique that can be borrowed for the home garden.
                    </p>
                    <p>
                    Soil pH is also a factor. Lavender grows best in neutral to alkaline soil with a pH of 6.5 to 8.2. Test your soil (turn to your local Cooperative Extension Service for assistance) to be sure.
                    </p>
                    <p>
                    Lavender only needs watering until it is established; it is otherwise drought-resistant.
                    </p>
                    <h3>
                    Temperature and Humidity
                    </h3>
                    <p>
                    If you live in a cold climate, USDA Hardiness Zone 4 or colder, lavender plants may not grow back the following spring unless you choose the hardiest varieties and offer winter protection.
                    </p>
                    <p>
                    Snow cover is one of the best insulators for tender plants. If you don&lsquo;t have a reliable amount of snow, protect your plants from winter damage by covering them with dry leaves or straw overlaid with burlap to protect them from drying winds and ice. Remove the covering in early spring to allow the soil to warm and give plants good air circulation.
                    </p>
                    <h3>
                    Fertilizer
                    </h3>
                    <p>
                    Lavender does not need to be fertilized, in fact, it does better in poor soil. Overfertilizing it can lead to excessive but week foliage growth and no flowers.
                    </p>
                    <h3>
                    Pruning
                    </h3>
                    <p>
                    Wait until lavender plants begin growing in spring to prune them. Prune about one third to one half of the plant; if you cut it back so hard that only woody stems show, the plant may die.
                    </p>
                    <p>
                    After the first flowering, deadheading (removing the spent flower stem) may encourage some plants to rebloom. You can lightly shape the plant at this time but hold off on major pruning until the following spring. Even with the best of care, recognize that lavender plants are short lived, lasting 10 to 15 years at most. 
                    </p>
                    <p>
                    To harvest lavender, gather blossoms when they have just opened. Use individual blooms fresh, discarding the little brown or green caps that hold them to the stems. Or cut entire flower stems to dry
                    </p>
                    <h3>
                    Potting and Repotting Lavender
                    </h3>
                    <p>
                    Gardeners with little in-ground growing space or heavy soil may want to grow lavender in pots. Choose a pot that&lsquo;s just slightly larger than the root ball with a drainage hole. Clay pots offer better air circulation and dry out faster than plastic or ceramic pots. Plant in a soilless potting mix such as one designed for growing cactus or succulents to ensure excellent drainage.
                    </p>
                    <p>
                    Water sparingly but don&lsquo;t let the plants dry out completely. If you use a saucer below the pot, always drain off excess water. Keep the pots in full sun outdoors. You can grow lavender indoors, but recognize that the amount of light inside a house may never be enough to get flowers.
                    </p>
                  </section>

                  <section name="problem">
                    <div className="flex items-center space-x-2">
                      <span className="text-2xl font-semibold">
                      Pests and Problems
                      </span>
                    </div>
                    <p>
                    Lavender doesn&lsquo;t have any major pests, but root rot and leaf spot can bother this herb. Avoid overwatering and maintain good air circulation to minimize these problems.
                    </p>
                  </section>

                  <section name="propagation">
                    <div className="flex items-center space-x-2">
                      <span className="text-2xl font-semibold">
                      How to Propagate Lavender
                      </span>
                    </div>
                    <p>
                    Lavender can be grown from seed, but it takes up to three years to grow into a substantial enough size for harvesting. Start with seeds from a seed catalog. Because most lavandin lavenders are a cross of two species, you won’t get good results with seeds that you collected from your own plants.
                    </p>
                    <p>
                    To get a head start on the growing season, it&lsquo;s a good idea to start seeds indoors. Plant lavender seeds 1 inch apart, just barely covered with a seed-starting potting mix and keep the container moist but not waterlogged in a warm (65 to 70 degrees F) location. Germination starts in two to four weeks.
                    </p>
                    <p>
                    When plants reach 2 to 3 inches tall, lavender seedlings should be acclimated to outdoor conditions
by gradually increasing the amount of light they receive. Once they are &quot;hardened off,&quot; plant them outdoors in a sunny, well-drained spot.
                    </p>
                    <p>
                    Most lavenders, especially lavandin, are started from cuttings instead of seeds. cut a 4- to 6-inch stem from a healthy plant in the late spring or early summer. Remove all the leaves from the bottom third of the cutting. Dip the cut end in rooting hormone powder and insert it in a 4-inch pot filled with damp potting mix. Place the pot in a sunny location and keep the soil evenly moist. After two to three months, when you gently tug on the cutting and it does not move, roots have formed. Wait for the plant to show some vigorous new growth before planting it in a larger pot or in the landscape.
                    </p>
                    
                  </section>

                  <section name="type">
                    <div className="flex items-center space-x-2">
                      <span className="text-2xl font-semibold">
                      Types of Lavender
                      </span>
                    </div>
                    <p>
                    There are many species and hundreds of lavender varieties. Here are a few of the best to grow in gardens.
                    </p>
                    <h3>
                    English Lavender
                    </h3>
                    <p>
                    Considered one of the hardiest lavender, English lavender (Lavandula angustifolia) has dozens of cultivars to choose from. Popular English lavenders include &lsquo;Munstead&lsquo; and &lsquo;Hidcote&lsquo;. They grow well in locations with mild summer heat in Zones 5-9 and reach about 2 feet in height.
                    </p>
                    <h3>
                    Lavandin
                    </h3>
                    <p>
                    These popular lavender types are a cross (Lavandula x intermedia) between English lavender and spike lavender (Lavandula latifolia). Lavandin is equally hardy, usually to Zone 5. Due to its larger flower spike size, this type of lavender is often grown commercially for essential oils.
                    </p>
                    <h3>
                    Spanish Lavender
                    </h3>
                    <p>
                    A lavender that works well in warmer climates (down to Zone 7), Spanish lavender (Lavandula stoechas) has large gray-green leaves and a stout, cylindrical flower head. These are often the earliest lavenders to bloom.
                    </p>
                  </section>

                  <section name="faq">
                    <div className="flex items-center space-x-2">
                      <span className="text-2xl font-semibold">
                      Frequently Asked Questions
                      </span>
                    </div>
                    <dl className="w-full mt-6 space-y-4 ">
                    {accordionData.map((data, index) => {
                      return (
                        <DropItem
                          key={index}
                          open={index === open}
                          title={data.title}
                          desc={data.desc}
                          toggle={() => toggle(index)}
                        />
                      );
                    })}
                  </dl>
                    
                  </section>

                </article>
              </section>
            </div>
          </div>
        </div>
        <div className="flex flex-row w-full">
        <div className="flex  w-full items-center justify-center relative">
        <div className="flex  pb-18 max-w-sm md:max-w-2xl ">
        <PopularPlant />
        </div>
        </div>
        </div>
      </div>

      <Footer />
    </>
  );
}