import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import Header from "../components/Header";
import Footer from "../components/Footer";
import GoTop from "../components/GoTop";

import cat1 from "@/assets/blogs/cat1.png";
import cat2 from "@/assets/blogs/cat2.png";
import cat3 from "@/assets/blogs/cat3.png";
import cat4 from "@/assets/blogs/cat4.png";
import cat5 from "@/assets/blogs/cat5.png";
import cat6 from "@/assets/blogs/cat6.png";
import cat7 from "@/assets/blogs/cat7.png";
import cat8 from "@/assets/blogs/cat8.png";
import cat9 from "@/assets/blogs/cat9.png";
import cat10 from "@/assets/blogs/cat10.png";
import cat11 from "@/assets/blogs/cat11.png";
import cat12 from "@/assets/blogs/cat12.png";

import bg from "@/assets/blogs/bg3.png";
import bg1 from "@/assets/blogs/bg1.png";
import Pagination from "../components/Pagination";

export default function Category() {
  const blogs = [
    {
      title:
        "10 most wanted Philodendron varieties - selected by our community",
      url: "best-smartwatch-iphone",
      image: cat1,
    },
    {
      title: "How to decorate with pink: a touch of pink never hurts!",
      url: "best-smartwatch-iphone",
      image: cat2,
    },
    {
      title: "General plant care guide",
      url: "best-smartwatch-iphone",
      image: cat3,
    },
    {
      title:
        "10 most wanted Philodendron varieties - selected by our community",
      url: "best-smartwatch-iphone",
      image: cat4,
    },
    {
      title: "A Simple Guide For Snake Plant Propagation",
      url: "best-smartwatch-iphone",
      image: cat5,
    },
    {
      title: "Anthurium Crystallinum Growing And Care",
      url: "best-smartwatch-iphone",
      image: cat6,
    },
    {
      title: "12 pretty plants that grow as an epiphyte ",
      url: "best-smartwatch-iphone",
      image: cat7,
    },
    {
      title: "Alocasia Propagation Guide: How To Propagate Alocasia Plants",
      url: "best-smartwatch-iphone",
      image: cat8,
    },
    {
      title: "12 pretty plants that grow as an epiphyte ",
      url: "best-smartwatch-iphone",
      image: cat7,
    },
    {
      title: "Alocasia Propagation Guide: How To Propagate Alocasia Plants",
      url: "best-smartwatch-iphone",
      image: cat8,
    },
    {
      title: "12 pretty plants that grow as an epiphyte ",
      url: "best-smartwatch-iphone",
      image: cat7,
    },
    {
      title: "Alocasia Propagation Guide: How To Propagate Alocasia Plants",
      url: "best-smartwatch-iphone",
      image: cat8,
    },
    {
      title:
        "What is an epiphyte and which epiphyte plants are the prettiest? ",
      url: "best-smartwatch-iphone",
      image: cat9,
    },
    {
      title: "Top 15 shadow plants in 2024",
      url: "best-smartwatch-iphone",
      image: cat10,
    },
    {
      title: "Greenhouse Cabinets 101: the basics",
      url: "best-smartwatch-iphone",
      image: cat11,
    },
    //   {
    //     title: "Top 10 hanging plants in 2024",
    //     url: "best-smartwatch-iphone",
    //     image: cat12,
    //   },
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />

      <main className="mx-auto max-w-[120rem]">
        <div className="relative z-0 w-full overflow-hidden bg-grayish h-[230px] md:h-[363px]">
          <Image src={bg} alt="" className=" object-cover h-full" />

          <div className="absolute bottom-3 left-3 w-3/4 overflow-hidden lg:left-0 xl:bottom-8">
            <span className="block">
              <span className="relative z-10 h-[32px] box-decoration-clone px-3 py-2 font-serif leading-[2.6rem] md:leading-[3rem] lg:h-[76px] lg:px-6 lg:py-4 lg:leading-[4.9rem] xl:h-24 3xl:leading-[7rem] bg-white/85 text-black/[.99] text-xl md:text-3xl lg:text-6xl font-bold">
                Grow your home with PLNTS
              </span>
            </span>
          </div>
        </div>

        <section className="mb-8 py-8 bg-white ">
          <div className="mx-auto md:max-w-3xl w-11/12">
            <h2 className="flex w-full font-bold text-2xl md:text-2xl justify-center text-gray-900">
              All blogs lined up
            </h2>
            <div className="mx-auto flex w-full max-w-4xl items-center justify-between pb-8 pt-8">
              <button
                className="cursor-pointer inline-block2 leading-none select-none text-center focus:outline-none transition-colors disabled:cursor-not-allowed max-h-10 relative mr-4 text-gray-300 flex justify-center p-0 px-0"
                disabled=""
                type="button"
                data-variant="null_null"
              >
                {" "}
                <svg
                  className="w-6 h-6 md:w-7 md:h-7 text-gray-900 rounded-full bg-white p-1 md:rounded-none md:bg-transparent md:p-0"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M15 19l-7-7 7-7"
                  ></path>
                </svg>
              </button>
              <div className="overflow-hidden">
                <div className="flex max-w-full gap-3">
                  <button
                    className="cursor-pointer inline-block leading-none select-none text-center focus:outline-none transition-colors disabled:cursor-not-allowed max-h-10 relative rounded-full border p-0 border-black"
                    type="button"
                    data-variant="rounded_null"
                  >
                    {" "}
                    <span className="flex h-full text-gray-900 min-w-10 items-center justify-center px-3 py-1.5 md:p-4">
                      All
                    </span>
                  </button>
                  <button
                    className="cursor-pointer inline-block leading-none select-none text-center focus:outline-none transition-colors disabled:cursor-not-allowed max-h-10 relative rounded-full border p-0 border-white"
                    type="button"
                    data-variant="rounded_null"
                  >
                    {" "}
                    <span className="flex h-full text-gray-900 min-w-10 items-center justify-center px-3 py-1.5 md:p-4">
                      Inspiration
                    </span>
                  </button>
                  <button
                    className="cursor-pointer inline-block leading-none select-none text-center focus:outline-none transition-colors disabled:cursor-not-allowed max-h-10 relative rounded-full border p-0 border-white"
                    type="button"
                    data-variant="rounded_null"
                  >
                    {" "}
                    <span className="flex h-full text-gray-900 min-w-10 items-center justify-center px-3 py-1.5 md:p-4">
                      Tips
                    </span>
                  </button>
                </div>
              </div>
              <button
                className="cursor-pointer inline-block2 leading-none select-none text-center focus:outline-none transition-colors disabled:cursor-not-allowed max-h-10 relative ml-4 flex justify-center p-0 px-0"
                type="button"
                data-variant="null_null"
              >
                {" "}
                <svg
                  className="w-6 h-6 md:w-7 md:h-7 text-gray-900 rounded-full bg-white p-1 md:rounded-none md:bg-transparent md:p-0"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M9 5l7 7-7 7"
                  ></path>
                </svg>
              </button>
            </div>
            <div className="grid w-full grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3">
              {blogs.map((data, index) => {
                return (
                  <Link
                    className="group relative block h-50 hover:underline"
                    key={index}
                    href={"/category/article-one"}
                  >
                    <Image
                      src={data.image}
                      alt=""
                      className="transform object-cover transition-transform group-hover:scale-105 h-full"
                    />
                    <span className="absolute bottom-0 m-3 block bg-white/80 p-3 font-serif text-gray-900">
                      {data.title}
                    </span>
                  </Link>
                );
              })}
            </div>
            <Pagination />
          </div>
        </section>
      </main>
    </>
  );
}
