import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import Header from "../components/Header";
import Footer from "../components/Footer";
import GoTop from "../components/GoTop";

import about from "@/assets/img/about.png";
import about1 from "@/assets/img/about1.png";
import about2 from "@/assets/img/about2.png";
import about3 from "@/assets/img/about3.png";
import about4 from "@/assets/img/about4.png";


export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
<GoTop />
      <div>
        <Image src={about} alt="" />
      </div>

      <div className="max-w-screen-xl mt-0 px-8 grid gap-8 grid-cols-1 md:grid-cols-2 md:px-12 lg:px-16 xl:px-32 py-16 mx-auto bg-white text-gray-900 rounded-lg shadow-lg">
        <div className="flex flex-col space-y-4">
          <div className="flex flex-col space-y-3">
            <div className="text-4xl text-gray-900 font-semibold">
              More plants, more green spaces!
            </div>
            <div className="markdown-blog">
              <article className="flex flex-col space-y-6">
                <span className="text-lg">
                  Greenspaces.id is a company established in October 2019 which
                  is engaged in the production and sale of ornamental plants
                  such as Arecaceae, Hoya, and Succulents. Our company is one of
                  the struggling companies during the pandemic which at that
                  time caused many businesses to collapse and people lost their
                  jobs. So that one of our missions is to help affected people
                  during the pandemic, especially farmers and young people to be
                  able to stay productive and reach their future. And our big
                  mission is to participate in being part of the sustainability
                  of this planet in a simple way, by spreading ornamental plants
                  throughout the world, thus creating a better and greener
                  environment.
                </span>
                <span className="text-lg">
                  The ornamental plant community is extraordinary and always
                  keeps us learning to always do the best for all the plants we
                  have. So that we can provide you with the best plants. All of
                  this can be done because we have professional farmers who are
                  experts in their fields, some of them even experienced for
                  more than 23 years.
                </span>
              </article>
            </div>
          </div>
        </div>
        <div className="flex flex-col space-y-2">
          <Image src={about2} alt="" />
          <Image src={about4} alt="" />
        </div>
      </div>
      <div className="max-w-screen-xl mt-0 px-8 flex flex-col md:flex-row space-y-6 md:space-y-0 md:space-x-10 items-center md:px-12 lg:px-16 xl:px-32 py-16 mx-auto bg-white text-gray-900 rounded-lg shadow-lg">
      <div className="w-full md:w-1/2 flex flex-col space-y-2">
          <Image src={about1} alt="" className="w-full h-96 object-cover" />
        </div>
        <div className="w-full md:w-1/2 flex flex-col space-y-4">
          <div className="flex flex-col space-y-3">
            <div className="text-4xl text-gray-900 font-semibold">
            Grown with Love
            </div>
            <div className="markdown-blog">
              <article className="flex flex-col space-y-6">
                <span className="text-lg">
                Our plants are cultivated and planted in nurseries by experienced farmers with more than 23 years of love and care. Then, our farmers will select the healthiest plants and send it to you. We care about your satisfaction, so having a professional farmer is a must!
                </span>
              </article>
            </div>
          </div>
        </div>
        
      </div>

      <div className="max-w-screen-xl mt-0 px-8 flex flex-col md:flex-row space-y-6 md:space-y-0 md:space-x-10 items-center md:px-12 lg:px-16 xl:px-32 py-16 mx-auto bg-white text-gray-900 rounded-lg shadow-lg">
      
        <div className="w-full md:w-1/2 flex flex-col space-y-4">
          <div className="flex flex-col space-y-3">
            <div className="text-4xl text-gray-900 font-semibold">
            Direct from the Greenhouse
            </div>
            <div className="markdown-blog">
              <article className="flex flex-col space-y-6">
                <span className="text-lg">
                Our plants are specially prepared directly from our Greenhouse. Everything sent has been checked for its health, such as the leaves, stems, and roots. So, you can be sure that the sent plants are in the best condition.
                </span>
              </article>
            </div>
          </div>
        </div>
        <div className="w-full md:w-1/2 flex flex-col space-y-2">
          <Image src={about} alt="" className="w-full h-96 object-cover" />
        </div>
      </div>

      <div className="max-w-screen-xl mt-0 px-8 flex flex-col md:flex-row space-y-6 md:space-y-0 md:space-x-10 items-center md:px-12 lg:px-16 xl:px-32 py-16 mx-auto bg-white text-gray-900 rounded-lg shadow-lg">
      <div className="w-full md:w-1/2 flex flex-col space-y-2">
          <Image src={about3} alt="" className="w-full h-96 object-cover" />
        </div>
        <div className="w-full md:w-1/2 flex flex-col space-y-4">
          <div className="flex flex-col space-y-3">
            <div className="text-4xl text-gray-900 font-semibold">
            Packed with care
            </div>
            <div className="markdown-blog">
              <article className="flex flex-col space-y-6">
                <span className="text-lg">
                Our plants are packaged professionally with great care and adjust to the weather conditions in the customer&lsquo;s destination country so that the plants are in a safe condition during the shipping and will arrive safely. We use plant-safe wrappings and insulations to keep them at a stable temperature. We also receive special requests from customers regarding how to pack plants which according to the customer is better.
                </span>
              </article>
            </div>
          </div>
        </div>
        
      </div>

      <Footer />
    </>
  );
}
