import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import Header from "../components/Header";
import Footer from "../components/Footer";
import GoTop from "../components/GoTop";

export default function Return() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />

      <div className="flex bg-[#f3f4f3] min-h-screen pt-10 pb-10 md:pt-[100px]">
        <div className="flex mx-auto w-11/12 md:w-10/12 bg-white rounded-md shadow border">
          <div className="flex py-10 flex-col space-y-10 mx-auto w-10/12">
            <div>
              <span className="text-3xl md:text-4xl font-bold md:leading-snug text-gray-900">
                Return Policy
              </span>
            </div>
            <section className="w-full mx-auto  markdown-blog">
              <article>
                <p className="text-lg  leading-snug text-gray-700">
                  Are you not completely satisfied with your purchase? You have
                  the right to return the product(s) you bought at PLNTS.com
                  within 14 days of receiving them. We will give you a full
                  refund of the purchased item(s). However, perishable products,
                  such as plants, are exempt from this right. Unfortunately,
                  this means that it is not possible to return plants.
                </p>

                <p>
                  Did your plant arrive in bad condition or is there something
                  else wrong with your new green roommate? Please use the yellow
                  support widget at the bottom left on our website to contact
                  our customer service. We will do everything we can to make
                  both you and your plant happy again!
                </p>

                <p>
                  Please download the following return form, fill it in and send
                  it back with the items you would like to return.
                </p>

                <h3>A few more things:</h3>
                <p>
                  As a customer, you are responsible for the return shipping
                  costs. As soon as we receive your return package, we will
                  start processing your refund request. Please note that you
                  will not be reimbursed for the original shipping costs. Any
                  refunds made by us will be issued back to the payment method
                  that you used to place your order.
                </p>

                <p>
                  Would you like to exchange a plant pot or another
                  non-perishable product for a different colour or size? Please
                  send the item(s) back to us and place a new order. We will
                  refund the money for the returned item (but not the transport
                  costs) as soon as possible.
                </p>

                <p>
                  The items you wish to return are your responsibility until we
                  receive them. If possible, re-use the original packaging for
                  returning your order and make sure all items are well packed.
                  We cannot compensate for products that were lost or damaged
                  during transportation.
                </p>
              </article>
            </section>
          </div>
        </div>
      </div>

      <Footer />
    </>
  );
}
