import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import GoTop from "@/app/components/GoTop";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";

import img from "@/assets/blogs/blog.png";
import RelatedArticle from "@/app/components/RelatedArticle";
import Help from "@/app/components/Help";
import Tags from "@/app/components/Tags";
import ShareIt from "@/app/components/ShareIt";
import AuthorBubble from "@/app/components/AuthorBubble";

export default function Detail() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />
      <ShareIt />

      <div className="flex flex-col bg-white min-h-screen ">
        <div
          className="flex relative justify-center flex-row w-full"
          style={{
            backgroundImage: `url(${img.src}) `,
            backgroundPosition: "center",
            backgroundSize: "cover",
            backgroundRepeat: "no-repeat",
            width: "100%",
            height: "100%",
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center'
          }}
        >
          <div className="flex flex-1 bottom-0 flex-col h-[260px] md:h-[400px] items-center justify-center bg-gray-600/30 backdrop-brightness-75">
            <div className="flex flex-1 flex-col pb-18 max-w-md md:max-w-2xl ">
              <section className="w-full mx-auto  mt-0 md:mt-2 px-5 z-40">
                {/* breadcrumb */}
                <nav className="text-sm my-1" aria-label="Breadcrumb">
                  <ol className="list-none p-0 inline-flex">
                    <li className="flex items-center">
                      <a
                        href="#"
                        className="uppercase text-white font-semibold md:font-bold hover:underline"
                      >
                        Gardening
                      </a>
                      <svg
                        className="fill-current text-white w-3 h-3 mx-1"
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 320 512"
                      >
                        <path d="M285.476 272.971L91.132 467.314c-9.373 9.373-24.569 9.373-33.941 0l-22.667-22.667c-9.357-9.357-9.375-24.522-.04-33.901L188.505 256 34.484 101.255c-9.335-9.379-9.317-24.544.04-33.901l22.667-22.667c9.373-9.373 24.569-9.373 33.941 0L285.475 239.03c9.373 9.372 9.373 24.568.001 33.941z" />
                      </svg>
                    </li>
                    <li>
                      <a
                        href="#"
                        className="text-white uppercase font-semibold md:font-bold hover:underline"
                        aria-current="page"
                      >
                        HOW TO GARDEN
                      </a>
                    </li>
                  </ol>
                </nav>
                <div className="flex flex-col space-y-1 pt-3 pb-0 ">
                  <h1 className="text-2xl leading-tight md:text-4xl font-semibold md:font-bold text-white">
                    6 Signs Of Overwatered Peace Lily (And Step By Step Fixes)
                  </h1>
                  <div className="flex items-center space-x-3">
                    <AuthorBubble />
                    <div>
                      <span className="text-sm text-white">
                        Updated October 2, 2023
                      </span>
                    </div>
                  </div>
                  
                </div>
              </section>
            </div>
          </div>
        </div>

        <div className="flex flex-row w-full">
          <div className="flex flex-1 flex-col items-center justify-center relative">
            <div className="flex flex-1 flex-col pb-18 max-w-md md:max-w-2xl ">
              <section className="w-full mx-auto  mt-0 md:mt-0 px-5 markdown-blog">
                <article>
                  <p>
                    Peace lilies are a highly popular houseplant, both for their
                    foliage and flowers.
                  </p>
                  <p>
                    These plants don’t require a huge amount of maintenance and
                    are relatively resistant to pests and disease when properly
                    tended to.
                  </p>
                  <p>
                    However, they’re prone to illness and infestations when
                    improperly watered.
                  </p>
                  <p>
                    As overwatering is perhaps the single biggest mistake plant
                    lovers make regularly, it’s essential to know the signs of
                    overwatering, address them, and what to do in severe cases.
                  </p>
                  <h2>6 Signs Of Overwatered Peace Lily</h2>
                  <p>
                    The following symptoms don’t always equate to overwatering
                    but are a good indicator. Try to eliminate other possible
                    causes of these signs and follow the remedies we’ve included
                    to solve each symptom.
                  </p>
                  <h3>Soggy Soil</h3>
                  <p>
                    Perhaps the single most obvious sign of overwatering is the
                    soil itself. You should never see puddles forming, nor
                    should the soil feel squishy to the touch.
                  </p>
                  <p>
                    Additionally, many factors affect how much and how often
                    your plant will drink, so watering on a schedule is one of
                    the worst things you can do. The soak-and-dry method is
                    perhaps the most effective way to water plants, with few
                    exceptions.
                  </p>
                  <p>Follow these steps:</p>
                  <ol className="list-disc">
                    <li>
                      Simply stick your finger in the soil to judge how far down
                      it feels dry.
                    </li>
                    <li>
                      Water for peace lilies when it feels dry 2″ inches down.
                    </li>
                    <li>
                      Always water slowly, working your way around the pot and
                      doing your best not to get the leaves wet.
                    </li>
                    <li>
                      Stop watering when you see moisture seeping from the
                      drainage holes, or the surface can no longer absorb at the
                      same speed you’re pouring.
                    </li>
                  </ol>
                  <h3>Yellowing Leaves</h3>
                  <p>
                    In the language of plants, this sign is the equivalent of a
                    human saying, “I don’t feel so well.” However, it’s not
                    difficult to verify this is being caused by overwatering by
                    checking the soil when you see yellowing leaves.
                  </p>
                  <p>
                    Some other common causes of yellow leaves include the
                    following:
                  </p>

                  <ol className="list-disc">
                    <li>Sunburn</li>
                    <li>Infestations</li>
                    <li>Root rot</li>
                  </ol>
                  <p>
                    Follow the soil care guide below once you confirm the
                    problem is being caused by overwatering. Chances are, many
                    of the leaves will regain their color, but some may be too
                    far gone and will need to be pruned away.
                  </p>
                  <h3>Blisters</h3>
                  <p>
                    When you spend too long in a tub or pool, your skin will
                    become so saturated that it wrinkles. Plants suffer a
                    similar condition called edema, in which the roots are
                    drawing more water than the plant can use.
                  </p>
                  <p>
                    As a result, the excess water fills leaf cells until they
                    burst, causing blister-like abscesses that can be found
                    mainly on the undersides of the leaves.
                  </p>
                  <p>
                    This is one of those conditions where you will likely need
                    to repot the plant. The blisters can eventually burst, and
                    you may find it necessary to prune away the worst leaves.
                  </p>

                  <h3>Brown Or Black Leaf Tips</h3>
                  <p>
                    Commonly associated with chemical burns from fertilizers or
                    sunburn, brown to black lea tips may also be related to
                    overwatering.
                  </p>
                  <p>
                    Unfortunately, this damage cannot be reversed. Some
                    yellowing and black means that part of the plant has turned
                    necrotic. The only treatment for this symptom is to remove
                    the damaged leaves.
                  </p>
                  <h3>Fungus Gnats Or Oddly-Tinted Soil</h3>
                  <p>
                    Fungus gnats are tiny insects that serve as pollinators for
                    some plants but are largely pests. These little guys can be
                    a sign of overwatering, as the larvae feed on soil-based
                    fungi.
                  </p>
                  <p>
                    Depending on the fungus, you might not be able to see it, or
                    you might see a greenish tint or gray to white cottony film
                    on the surface.
                  </p>
                  <p>
                    These problems can often be solved using a neem soil soak
                    and possibly also fungicide (although neem oil will kill
                    some forms of fungus).
                  </p>
                  <h3>Root Rot</h3>
                  <p>
                    Root rot is the worst-case scenario, and it can kill your
                    plant if left untreated. In addition to yellowed, droopy
                    leaves, you’ll likely smell a foul odor coming from the
                    soil. Either bacteria or fungus may cause root rot, so you
                    can’t rely on fungicides to treat it.
                  </p>
                  <p>
                    You’ll have to dig up the plant, remove the damaged roots,
                    sterilize the surviving roots, and plant it in a fresh pot
                    with fresh soil to treat root rot.
                  </p>
                  <p>
                    Note that neem soil soaks have been known to help fight off
                    both bacterial and fungal root rot in its early stages but
                    will not be able to save a plant once the condition begins
                    to worsen.
                  </p>

                  <h2>How To Treat Severe Overwatering?</h2>
                  <p>
                    In most of the above cases, you can stop watering to allow
                    the soil to dry out, but what happens when the damage is a
                    bit more severe, or the plant has been overwatered
                    repeatedly?
                  </p>
                  <p>
                    Treating severe overwatering means acting fast and
                    completely repotting the plant.
                  </p>

                  <h3>Step 1: Remove The Wet Soil</h3>
                  <p>
                    Tip the pot over and slide the plant out, gently removing as
                    much dirt from the roots as possible. Now is a good time to
                    check for root rot and treat it, if necessary. It’s often
                    good to let the plant dry out a little for 8 hours (or
                    overnight) in a warm, dry spot.
                  </p>
                  <h3>Step 2: Prepare A New Container</h3>
                  <p>
                    If your old pot has adequate drainage holes, you can soak it
                    in a solution of 1 part bleach to 9 parts water for 30
                    minutes and allow it to dry.
                  </p>
                  <p>
                    Otherwise, you’ll want to get a new container, making sure
                    the drainage holes are large enough and that the pot isn’t
                    too big or small for your plant.
                  </p>
                  <p>
                    To help ensure the best drainage, ad a ½ to 1” inch layer of
                    gravel or aquarium stones to the bottom of the pot.
                  </p>
                  <h3>Step 3: Prepare The Soil</h3>
                  <p>Here are the steps to prepare the soil:</p>

                  <ol className="list-disc">
                    <li>
                      Now you’ll want to add some fresh soil to the container.
                      Don’t use the old soil, as it’s likely contaminated.
                    </li>
                    <li>
                      Mix some perlite or coarse sand into the soil to help
                      ensure it remains loose, as compacted soil can contribute
                      to overwatering issues.
                    </li>
                    <li>
                      Add the soil to the container and give it a light
                      watering.
                    </li>
                  </ol>
                  <p>
                    You only need enough to get the soil slightly damp to help
                    things settle.
                  </p>

                  <h3>Step 4: Replant Your Peace Lily</h3>
                  <p>
                    Once the pot and soil are ready, you can replant your lily.
                    Ensure it’s planted at the same depth as before and give it
                    another light watering.
                  </p>
                  <p>
                    Note that the plant needs LESS water if you group it with
                    other plants, as over 97% percent of the water it absorbs is
                    used in transpiration (essentially sweating to improve local
                    humidity levels).
                  </p>
                  <p>
                    Grouped plants share the benefits of transpiration, reducing
                    the amount of water they need.
                  </p>
                  <p>
                    As long as you use the soak-and-dry method to water your
                    peace lily, overwatering should become a thing of the past.
                  </p>
                </article>
              </section>

              <Help />

              {/* SOURCE */}
              <div className="px-6 md:px-4 pt-4">
                <span className=" text-sm italic">
                  A version of this article was originally written by Clare
                  McHugh and first appeared on Health.com.
                </span>
              </div>
              <div className="md:text-sm text-gray-500 px-6 md:px-4 pb-3 font-mabry">
                Source:{" "}
                <a
                  href="https://mydramalist.com/article/an-ultra-fan-guide-to-lee-elijah"
                  className="italic underline font-mabryitalic"
                >
                  https://mydramalist.com/article/an-ultra-fan-guide-to-lee-elijah
                </a>
              </div>

              {/* <Tags /> */}
            </div>
          </div>
        </div>
        <div className="flex flex-row w-full">
          <div className="flex flex-1 w-full items-center justify-center relative">
            <div className="flex flex-1 pb-18  max-w-sm md:max-w-2xl ">
              <RelatedArticle />
            </div>
          </div>
        </div>
      </div>

      <Footer />
    </>
  );
}
