import React from 'react'
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

import Header from "../components/Header";
import Footer from "../components/Footer";
import GoTop from "../components/GoTop";

export default function Contact() {
  return (
    <>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />

      <div className="max-w-screen-xl mt-0 px-8 grid gap-8 grid-cols-1 md:grid-cols-2 md:px-12 lg:px-16 xl:px-32 py-16 md:py-24 mx-auto bg-white text-gray-900 rounded-lg shadow-lg">
        <div className="flex flex-col space-y-4">
          <div className="flex flex-col space-y-3">
            <h2 className="text-4xl lg:text-5xl font-bold leading-tight">
            Get in touch{" "}
            </h2>
            <div className="text-lg text-gray-700 font-semibold">
              We always love to hear from you!
            </div>
            <span>
              Get in touch with any questions, thoughts or comments or simply if
              you want a chat and one of the team will be back in touch.
            </span>
          </div>
          <div className="flex flex-col space-y-0">
            <div>hello@beonhand.co.uk</div>
            <span>0203 488 2912</span>
          </div>
        </div>
        <div className="flex flex-col space-y-2">
          <div>
            
            <input
              className="w-full bg-white border border-gray-400 placeholder:text-sm text-gray-900 mt-2 p-2 md:p-3 focus:outline-none focus:shadow-outline"
              type="text"
              placeholder="Name"
            />
          </div>
          <div className="">
            <input
              className="w-full bg-white border border-gray-400 placeholder:text-sm text-gray-900 mt-2 p-2 md:p-3 focus:outline-none focus:shadow-outline"
              type="text"
              placeholder='Email'
            />
          </div>
          <div className="">
            <textarea className="w-full h-32 bg-white border placeholder:text-sm border-gray-400 text-gray-900 mt-2 p-3 focus:outline-none focus:shadow-outline" placeholder='Comment'></textarea>
          </div>
          <div className="">
            <button className="text-md font-semibold tracking-wide bg-[#debe48] hover:opacity-80 text-white py-3 w-full focus:outline-none focus:shadow-outline">
              Send Message
            </button>
          </div>
        </div>
      </div>

      <Footer />
    </>
  )
}
