import Image from 'next/image'
import Head from 'next/head'
import Header from './components/Header'
import GoTop from './components/GoTop'
import Footer from './components/Footer'
import Hero from './components/Hero'

export default function Home() {
  return (
   <>
   <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />
      <Hero />
      <Footer />
   </>
  )
}
