import Image from 'next/image'
import Head from 'next/head'
import Header from './components/Header'
import GoTop from './components/GoTop'
import Footer from './components/Footer'
import Hero from './components/Hero'
import SubscribeForm from './components/SubscribeForm'
import AdsModal from './components/AdsModal'
import ArticleHome from './components/ArticleHome'
import CookieConsent from './components/CookieConsent'
import CategoryHome from './components/CategoryHome'

export default function Home() {
  return (
   <>
   <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />
      <CookieConsent />
      <Hero />
      <AdsModal />
      <ArticleHome />
      <CategoryHome />
      <SubscribeForm />
      <Footer />
   </>
  )
}
