import React from 'react'
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import Header from '../components/Header';
import Footer from '../components/Footer';
import GoTop from '../components/GoTop';
import PopularPlant from '../components/PopularPlant';

export default function Plant() {
    const letters = [
        {
            title: 'a',
            status: true
        },
        {
            title: 'b',
            status: true
        },
        {
            title: 'c',
            status: true
        },
        {
            title: 'd',
            status: true
        },
        {
            title: 'e',
            status: true
        },
        {
            title: 'f',
            status: true
        },
        {
            title: 'g',
            status: true
        },
        {
            title: 'h',
            status: true
        },
        {
            title: 'i',
            status: true
        },
        {
            title: 'j',
            status: true
        },
        {
            title: 'k',
            status: true
        },
        {
            title: 'l',
            status: true
        },
        {
            title: 'm',
            status: true
        },
        {
            title: 'n',
            status: true
        },
        {
            title: 'o',
            status: true
        },
        {
            title: 'p',
            status: true
        },
        {
            title: 'q',
            status: true
        },
        {
            title: 'r',
            status: true
        },
        {
            title: 's',
            status: true
        },
        {
            title: 't',
            status: true
        },
        {
            title: 'u',
            status: true
        },
        {
            title: 'v',
            status: true
        },
        {
            title: 'w',
            status: true
        },
        {
            title: 'x',
            status: true
        },
        {
            title: 'y',
            status: true
        },
        {
            title: 'z',
            status: true
        },
    ]

    const catBreeds = [
        "Abyssinian",
        "Aegean",
        "American Curl",
        "American Bobtail",
        "American Shorthair",
        "American Wirehair",
        "Arabian Mau",
        "Australian Mist",
        "Asian",
        "Asian Semi-longhair",
        "Balinese",
        "Bambino",
        "Bengal",
        "Birman",
        "Bombay",
        "Brazilian Shorthair",
        "British Semi-longhair",
        "British Shorthair",
        "British Longhair",
        "Burmese",
        "Burmilla",
        "California Spangled",
        "Chantilly-Tiffany",
        "Chartreux",
        "Chausie",
        "Cheetoh",
        "Colorpoint Shorthair",
        "Cornish Rex",
        "Cymric",
        "Cyprus",
        "Devon Rex",
        "Donskoy",
        "Dragon Li",
        "Dwarf cat",
        "Egyptian Mau",
        "European Shorthair",
        "Exotic Shorthair",
        "Foldex",
        "German Rex",
        "Havana Brown",
        "Highlander",
        "Himalayan",
        "Japanese Bobtail",
        "Javanese",
        "Karelian Bobtail",
        "Khao Manee",
        "Korat",
        "Korean Bobtail",
        "Korn Ja",
        "Kurilian Bobtail",
        "LaPerm",
        "Lykoi",
        "Maine Coon",
        "Manx",
        "Mekong Bobtail",
        "Minskin",
        "Munchkin",
        "Nebelung",
        "Napoleon",
        "Norwegian Forest cat",
        "Ocicat",
        "Ojos Azules",
        "Oregon Rex",
        "Oriental Bicolor",
        "Oriental Shorthair",
        "Oriental Longhair",
        "PerFold",
        "Persian (Modern Persian Cat)",
        "Persian (Traditional Persian Cat)",
        "Peterbald",
        "Pixie-bob",
        "Raas",
        "Ragamuffin",
        "Ragdoll",
        "Russian Blue",
        "Russian White, Black and Tabby",
        "Sam Sawet",
        "Savannah",
        "Scottish Fold",
        "Selkirk Rex",
        "Serengeti",
        "Serrade petit",
        "Siamese",
        "Siberian",
        "Singapura",
        "Snowshoe",
        "Sokoke",
        "Somali",
        "Sphynx",
        "Suphalak",
        "Thai",
        "Thai Lilac",
        "Tonkinese",
        "Toyger",
        "Turkish Angora",
        "Turkish Van",
        "Ukrainian Levkoy"
      ]

  return (
    <>
       <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <GoTop />

      <PopularPlant />

      <div className="h-max mx-auto w-full lg:w-1/2 flex flex-col space-y-3 px-3 md:px-6 lg:px-0 py-0 md:py-4 justify-center2 items-center2 bg-white">
            <div>
                <span className='font-semibold text-black'>Find a topic by its first letter:</span>
            </div>
            <div className="flex flex-wrap justify-left mx-auto w-full md:w-12/12  items-center">
                {letters.map((data,index) => {
                    return (
<Link href={""} key={index} className='flex mr-2 mt-2 justify-center items-center mb-1.5 w-8 h-8 hover:bg-blue-800 px-2 py-1 border-2 text-gray-900 hover:text-white border-gray-900'>
                    <span className='uppercase font-bold'>{data.title}</span>
                </Link>
                    )
                })}
                
            </div>
        </div>

        <div className="h-max mx-auto w-full lg:w-1/2 flex flex-col space-y-3 px-3 md:px-6 lg:px-0 py-0 md:pt-4 pb-20  justify-center2 items-center2 bg-white">
            <div className='py-2'>
                <span className='p-2 w-12 h-12 flex justify-center items-center bg-black text-white text-2xl font-bold'>A</span>
            </div>
            <div className='grid grid-cols-2 md:grid-cols-3 gap-4'>
                {catBreeds.map((data,index) => {
                    return (
                        <Link href={"/plant/lavender"} key={index} className='border-t py-1 border-slate-500 hover:underline hover:underline-offset-1 text-lg font-semibold text-black'>
                    <span className=''>{data}</span>
                </Link>
                    )
                })}
                
            </div>
        </div>

      <Footer />  
    </>
  )
}
