import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import Header from "../components/Header";
import Footer from "../components/Footer";
import GoTop from "../components/GoTop";

export default function Terms() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />

      <div className="flex bg-[#f3f4f3] min-h-screen pt-10 pb-10 md:pt-[100px]">
        <div className="flex mx-auto w-11/12 md:w-10/12 bg-white rounded-md shadow border">
          <div className="flex py-10 flex-col space-y-10 mx-auto w-10/12">
            <div>
              <span className="text-3xl md:text-4xl font-bold md:leading-snug text-gray-900">
                Terms & Conditions
              </span>
            </div>
            <div>
              <span className="text-lg  leading-snug text-gray-700">
                We understand that traditional education is important, but it is
                not enough to prepare you for the real world. That&apos;s why
                we&apos;ve created a full-cycle curriculum that goes beyond the
                boundaries of traditional education, providing you with the
                hands-on experience, mentorship, and support you need to turn
                your dreams into realities.
              </span>
            </div>

            <div className="ml-4">
              <span className="text-md  leading-snug text-gray-700">
                <ol className="list-decimal space-y-2">
                  <li>
                    We use a first in first out system for the shipment with the
                    capacity of 70-80 packages per week.
                  </li>
                  <li>
                    Damages from shipping are common when importing live plants,
                    if you feel unsure or not up for the risks, please consider
                    canceling or not ordering at all.
                  </li>
                  <li>
                    If there are permanent damages, please do not worry, we will
                    be responsible, prepare the proof of damages such as photos
                    and videos of the damaged plants, and send them to our email
                    support@greenspaces.id.
                  </li>
                  <li>
                    Reporting cases to PayPal will delay the problem-solving
                    further, so please remain calm, contact us, and be patient
                    if any problem occurs, we will reach out to you as soon as
                    possible after claims are made.
                  </li>
                  <li>
                    Refunds are only eligible for those who have enough proof of
                    damages and can only be done if all the requirements are
                    met, if there is any case being raised, we will not hesitate
                    to delay the process.
                  </li>
                  <li>
                    Resend is also eligible for those who have enough proof of
                    damages and can only be done if all the requirements are
                    met. There will be a $45 shipping fee for the resend, but it
                    is negotiable if there’s some conditions, please contact us
                    for more information.
                  </li>
                  <li>
                    Order cancellations cannot be processed after 3 days after
                    the order has been made, exceptions are only acceptable
                    under some circumstances.
                  </li>
                  <li>
                    All form of import fee, taxes, and duty fees are out of our
                    control, it is charged by the courier and it is customer’s
                    responsibility to pay, we will not take any liability for
                    any problem in regard of the taxes.
                  </li>
                  <li>
                    Indonesian regulation requires a phytosanitary certificate
                    for exporting, so please always include it in your order.
                  </li>
                  <li>
                    Please provide us with an Import Permit and a Green/Yellow
                    label for your imports.
                  </li>
                </ol>

                <div className="py-2">
                  More information is available through these websites;
                </div>
                <div className="py-2 underline underline-offset-1 font-semibold ">
                  US for any number plants:
                </div>
                <ul className="list-disc space-y-2">
                  <li>
                    Import Permit:
                    <p className="truncate...">https://www.aphis.usda.gov/aphis/resources/sa_epermits/sa_plants/ppq-epermits</p>
                  </li>
                  <li>
                    Green Labels :
                    <p className="truncate...">https://www.aphis.usda.gov/aphis/ourfocus/planthealth/import-information/permits/plants-and-plant-products-permits/plants-plantproducts-shipping-labels</p>
                  </li>
                </ul>

                <div className="py-2 underline underline-offset-1 font-semibold ">
                  Canada for any number plants:
                </div>
                <ul className="list-disc">
                  <li>
                  <p className="truncate...">https://www.trade.gov/country-commercial-guides/canada-import-requirements-and-documentation</p>
                  </li>
                </ul>
                <div className="py-2 underline underline-offset-1 font-semibold ">
                  UK and other EU Countries:
                </div>
                <ul className="list-disc space-y-2">
                  <li>
                  <p className="truncate...">https://www.daera-ni.gov.uk/articles/import-and-export-plants</p>
                  </li>
                  <li>
                  <p className="truncate...">https://www.gov.uk/guidance/import-of-products-animals-food-and-feed-system</p>
                  </li>
                  <li>
                  <p className="truncate...">https://business.gov.nl/regulation/phytosanitary-inspections/</p>
                  </li>
                </ul>
              </span>
            </div>
          </div>
        </div>
      </div>

      <Footer />
    </>
  );
}
