"use client"

import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";

import GoTop from "../components/GoTop";
import Header from '../components/Header'
import Footer from '../components/Footer'
import ProductSlider from "../components/ProductSlider";
import Review from "../components/Review";

export default function Detail() {
    const [count, setCount] = useState(0);

  const handleSubtractOne = () => {
    setCount(count - 1);
  };

  const handleAddOne = () => {
    setCount(count + 1);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />

      <div className="flex relative z-10 items-center overflow-hidden bg-white">
        <div className="flex w-full flex-col md:flex-row items-center2 justify-center2 bg-[#f1f1f3]">
          <div className="w-full md:hidden flex flex-col px-4 py-2 bg-transparent">
            <div>
              <nav className="text-sm my-1" aria-label="Breadcrumb">
                <ol className="list-none p-0 inline-flex">
                  <li className="flex items-center">
                    <a
                      href="#"
                      className="capitalize text-gray-900 hover:underline tracking-tight"
                    >
                      Product
                    </a>
                    <svg
                      className="fill-current text-gray-900 w-2 h-2 mx-1"
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 320 512"
                    >
                      <path d="M285.476 272.971L91.132 467.314c-9.373 9.373-24.569 9.373-33.941 0l-22.667-22.667c-9.357-9.357-9.375-24.522-.04-33.901L188.505 256 34.484 101.255c-9.335-9.379-9.317-24.544.04-33.901l22.667-22.667c9.373-9.373 24.569-9.373 33.941 0L285.475 239.03c9.373 9.372 9.373 24.568.001 33.941z" />
                    </svg>
                  </li>
                  <li className="flex items-center">
                    <a
                      href="#"
                      className="text-gray-900 capitalize hover:underline tracking-tight"
                      aria-current="page"
                    >
                      Treats
                    </a>
                    <svg
                      className="fill-current text-gray-900 w-2 h-2 mx-1"
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 320 512"
                    >
                      <path d="M285.476 272.971L91.132 467.314c-9.373 9.373-24.569 9.373-33.941 0l-22.667-22.667c-9.357-9.357-9.375-24.522-.04-33.901L188.505 256 34.484 101.255c-9.335-9.379-9.317-24.544.04-33.901l22.667-22.667c9.373-9.373 24.569-9.373 33.941 0L285.475 239.03c9.373 9.372 9.373 24.568.001 33.941z" />
                    </svg>
                  </li>
                  <li>
                    <a
                      href="#"
                      className="text-gray-900 font-semibold capitalize hover:underline tracking-tight"
                      aria-current="page"
                    >
                      Salmon Savory Chews
                    </a>
                  </li>
                </ol>
              </nav>
            </div>
            <div className="flex py-2">
              <div>
                <span className="text-3xl font-semibold leading-tight">
                  Salmon Savory Chews
                </span>
              </div>
            </div>
          </div>
          <div className="w-full md:w-1/2 h-full bg-[#f1f1f3]">
            <div className="flex h-full justify-center items-center">
              {/* <Image src={detail1} alt="" className="object-cover" /> */}
              <ProductSlider />
            </div>
          </div>
          <div className="w-full md:w-1/2 flex flex-col px-4 md:px-10 py-4 bg-[#f1f1f3]">
            <div className="hidden md:block">
              <nav className="text-sm my-1" aria-label="Breadcrumb">
                <ol className="list-none p-0 inline-flex">
                  <li className="flex items-center">
                    <a
                      href="#"
                      className="capitalize text-gray-900 hover:underline tracking-tight"
                    >
                      Product
                    </a>
                    <svg
                      className="fill-current text-gray-900 w-2 h-2 mx-1"
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 320 512"
                    >
                      <path d="M285.476 272.971L91.132 467.314c-9.373 9.373-24.569 9.373-33.941 0l-22.667-22.667c-9.357-9.357-9.375-24.522-.04-33.901L188.505 256 34.484 101.255c-9.335-9.379-9.317-24.544.04-33.901l22.667-22.667c9.373-9.373 24.569-9.373 33.941 0L285.475 239.03c9.373 9.372 9.373 24.568.001 33.941z" />
                    </svg>
                  </li>
                  <li className="flex items-center">
                    <a
                      href="#"
                      className="text-gray-900 capitalize hover:underline tracking-tight"
                      aria-current="page"
                    >
                      Treats
                    </a>
                    <svg
                      className="fill-current text-gray-900 w-2 h-2 mx-1"
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 320 512"
                    >
                      <path d="M285.476 272.971L91.132 467.314c-9.373 9.373-24.569 9.373-33.941 0l-22.667-22.667c-9.357-9.357-9.375-24.522-.04-33.901L188.505 256 34.484 101.255c-9.335-9.379-9.317-24.544.04-33.901l22.667-22.667c9.373-9.373 24.569-9.373 33.941 0L285.475 239.03c9.373 9.372 9.373 24.568.001 33.941z" />
                    </svg>
                  </li>
                  <li>
                    <a
                      href="#"
                      className="text-gray-900 font-semibold capitalize hover:underline tracking-tight"
                      aria-current="page"
                    >
                      Salmon Savory Chews
                    </a>
                  </li>
                </ol>
              </nav>
            </div>
            <div className="flex flex-col py-4 space-y-3">
              <div>
                <span className="text-3xl font-semibold leading-tight">
                  Salmon Savory Chews
                </span>
              </div>
              <div>
                <span className="text-2xl font-bold">$8.50</span>
              </div>
              <div>
                <span className="text-[17px] leading-tight">
                  Spoil your cat with confidence, courtesy of our simple jerky
                  treats. Kitty will love the big meaty flavor and chewy
                  texture, and you’ll feel good knowing that they’re free from
                  grains, fillers, and artificial ingredients.
                </span>
              </div>
            </div>
            <div className="py-4 md:py-6 flex flex-col">
              <div className="flex h-14 border-x-2 border-t-2 border-gray-900">
                <button
                  data-action="decrement"
                  onClick={handleSubtractOne}
                  className="flex bg-[#f1f1f3] text-gray-600 hover:text-gray-700 hover:bg-gray-200 h-full w-20 cursor-pointer outline-none"
                >
                  <span className="m-auto text-2xl font-thin">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      strokeWidth={1.5}
                      stroke="currentColor"
                      className="w-6 h-6"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M18 12H6"
                      />
                    </svg>
                  </span>
                </button>
                <input
                  type="number"
                  className="outline-none2 focus:outline-none text-center w-full bg-[#f1f1f3] font-semibold text-md hover:text-black focus:text-black  md:text-basecursor-default flex items-center text-gray-700  outline-none"
                  name="custom-input-number"
                  value={count}
                  readOnly
                ></input>
                <button
                  data-action="increment"
                  onClick={handleAddOne}
                  className="flex bg-[#f1f1f3] text-gray-600 hover:text-gray-700 hover:bg-gray-200 h-full w-20 cursor-pointer"
                >
                  <span className="m-auto text-2xl font-thin">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      strokeWidth={1.5}
                      stroke="currentColor"
                      className="w-6 h-6"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M12 6v12m6-6H6"
                      />
                    </svg>
                  </span>
                </button>
              </div>
              <button className="flex w-full items-center justify-center py-4 border-2 border-gray-900 bg-[#c7dbf0] hover:bg-[#8fb7e1]">
                <span className="uppercase text-[16px] font-semibold">
                  Add to cart
                </span>
              </button>
            </div>
            <div className="flex w-44  items-center space-x-2 mb-3 cursor-pointer hover:text-pink-500">
              <div>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="w-7 h-7"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z"
                  />
                </svg>
              </div>
              <span className="capitalize font-semibold text-[16px]">
                Add to favorite
              </span>
            </div>
            <div className="flex flex-col space-y-1">
              <div className="flex space-x-1 items-center">
                <div>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    strokeWidth={1}
                    stroke="currentColor"
                    className="w-6 h-6"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M8.25 18.75a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m3 0h6m-9 0H3.375a1.125 1.125 0 01-1.125-1.125V14.25m17.25 4.5a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m3 0h1.125c.621 0 1.129-.504 1.09-1.124a17.902 17.902 0 00-3.213-9.193 2.056 2.056 0 00-1.58-.86H14.25M16.5 18.75h-2.25m0-11.177v-.958c0-.568-.422-1.048-.987-1.106a48.554 48.554 0 00-10.026 0 1.106 1.106 0 00-.987 1.106v7.635m12-6.677v6.677m0 4.5v-4.5m0 0h-12"
                    />
                  </svg>
                </div>
                <span className="">Free shipping on orders of $50 or more</span>
              </div>
              <div className="flex space-x-1 items-center">
                <div>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    strokeWidth={1}
                    stroke="currentColor"
                    className="w-6 h-6"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0111.186 0z"
                    />
                  </svg>
                </div>
                <span>30-day Money Back Guarantee</span>
              </div>
            </div>
            <div className="flex flex-col space-y-2 py-5">
              <div>
                <span className="font-bold">Description</span>
              </div>
              <ul className="text-[15px] list-disc pl-5">
                <li>92% real, dehydrated salmon</li>
                <li>
                  Grain-free and low carb. No potatoes, corn, rice or wheat
                </li>
                <li>Satisfying chewy texture</li>
                <li>Resealable bag</li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <Review />

      <div className="w-full py-6 bg-secondary text-white md:bg-grayish md:text-black">
        <div className="grid-container grid w-full grid-cols-1 gap-3 md:grid-cols-12 xl:gap-4 px-3 xl:px-0">
          <div className="hidden justify-between md:flex col-span-full md:flex-row">
            <div className="flex flex-1 flex-col justify-start xl:flex-row xl:justify-end items-center">
              <svg
                className="h-18 flex-none xl:h-auto"
                xmlns="http://www.w3.org/2000/svg"
                width="91"
                height="76.535"
              >
                <g stroke="#141215" stroke-miterlimit="10" stroke-width="2">
                  <g fill="none">
                    <g transform="translate(23.249 63.453)">
                      <circle cx="6.041" cy="6.041" r="6.041"></circle>
                      <circle
                        cx="6.041"
                        cy="6.041"
                        r="6.041"
                        transform="translate(45.988)"
                      ></circle>
                    </g>
                    <path d="M69.52 30.012h10.406L90 41.319v17.074H15.385v-7.72"></path>
                    <path d="M64.639 53.453V19.115H14.753v8.943M5.039 33.073h21.113M0 38.754h21.113M5.039 44.436h21.113"></path>
                  </g>
                  <path
                    d="M36.358 17.744c3.88 1.714-20.321-.406-20.925-9.55-.262-3.981 3.589-7.4 7.258-7.181 6.519.395 9.375 14.833 13.667 16.731z"
                    fill="#f3f4f3"
                  ></path>
                  <path
                    d="M37.145 17.732c-1.557 2.222 10.992-6.949 8.3-12.156a4.555 4.555 0 00-6.35-1.529c-3.444 2.375-.228 11.225-1.95 13.685z"
                    fill="#f3f4f3"
                  ></path>
                  <path
                    d="M37.517 17.744c-3.88 1.714 20.321-.406 20.925-9.55.262-3.981-3.589-7.4-7.258-7.181-6.52.395-9.376 14.833-13.667 16.731z"
                    fill="#f3f4f3"
                  ></path>
                  <path
                    d="M26.485 32.478c2.262.022 5.756-1.055 7.864-7.765.674-2.144 1.851-5.521 3.675-6.833"
                    fill="none"
                  ></path>
                </g>
              </svg>
              <div className="[&amp;_p:first-of-type]:text-base [&amp;_p:first-of-type]:lg:text-3xl [&amp;_p:last-child]:text-sm [&amp;_p:last-child]:lg:text-base pl-3 xl:pl-6 mt-3 xl:mt-0">
                <p className="font-bold">Free shipping from €75,-</p>
                <p className="font-bold">We ship our plants all over Europe!</p>
              </div>
            </div>
            <svg
              className="flex-none mx-4 xl:mx-12 h-full w-px"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 1 100"
              preserveAspectRatio="none"
            >
              <path d="M0,0 0,100" stroke="#707070" stroke-width="1"></path>
            </svg>
            <div className="flex flex-1 flex-col justify-start xl:flex-row items-center">
              <svg
                className="h-18 flex-none xl:h-auto"
                xmlns="http://www.w3.org/2000/svg"
                width="64.688"
                height="83.675"
              >
                <path
                  d="M36.261 10.458c-1.082 1.081-3.917 3.21-3.917 3.21s-2.835-2.128-3.917-3.21a5.54 5.54 0 117.834 0zM32.344 13.668L.999 31.106c0 42.3 31.424 51.527 31.424 51.527s31.265-9.224 31.265-51.527z"
                  fill="none"
                  stroke="#141215"
                  stroke-miterlimit="10"
                  stroke-width="2"
                ></path>
                <g fill="#141215" stroke="#000">
                  <path d="M15.08 53.028l1.14-.941a7.592 7.592 0 006.213 3.193c2.679 0 4.931-1.8 4.931-4.418v-.057c0-2.793-2.623-4.332-6.213-4.332h-1.083l-.37-.826 6.868-7.923H16.107v-1.4h12.482v1.055l-6.753 7.723c3.791.229 7.068 2 7.068 5.643v.056c0 3.478-3.049 5.814-6.5 5.814a8.971 8.971 0 01-7.324-3.587zM32.773 46.359v-.053c0-5.5 3.221-10.316 8.292-10.316s8.237 4.759 8.237 10.259v.057c0 5.5-3.22 10.316-8.294 10.316s-8.235-4.763-8.235-10.263zm14.99 0v-.053c0-4.646-2.621-8.978-6.755-8.978s-6.7 4.275-6.7 8.92v.058c0 4.617 2.622 8.978 6.753 8.978s6.702-4.308 6.702-8.925z"></path>
                </g>
              </svg>
              <div className="[&amp;_p:first-of-type]:text-base [&amp;_p:first-of-type]:lg:text-3xl [&amp;_p:last-child]:text-sm [&amp;_p:last-child]:lg:text-base pl-3 xl:pl-6 mt-3 xl:mt-0">
                <p className="font-bold">30 day health guarantee</p>
                <p>
                  <span className="font-bold">For all our happy plants.</span>{" "}
                  <a
                    className="underline hover:no-underline"
                    href="/page/guarantee"
                  >
                    Read more about our guarantees
                  </a>
                  .
                </p>
              </div>
            </div>
          </div>
          <div className="md:hidden [&amp;_ul_li+li]:mt-5 [&amp;_ul_li]:before:mr-4 [&amp;_ul_li]:before:content-['\2713']">
            <ul>
              <li>
                Delivery <span className="font-bold">throughout Europe</span>
              </li>
              <li>
                <span className="font-bold">
                  Free shipping for orders over €75,-
                </span>
              </li>
              <li>
                <a
                  className="underline hover:no-underline"
                  href="/page/guarantee"
                >
                  <span className="font-bold">30 day</span> PLNTS health
                  guarantee
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <Footer />
    </>
  );
}
