import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import Header from "../components/Header";
import Footer from "../components/Footer";
import GoTop from "../components/GoTop";

export default function Privacy() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />

      <div className="flex bg-[#f3f4f3] min-h-screen pt-10 pb-10 md:pt-[100px]">
        <div className="flex mx-auto w-11/12 md:w-10/12 bg-white rounded-md shadow border">
          <div className="flex py-10 flex-col space-y-10 mx-auto w-10/12 markdown-blog">
            <div>
              <span className="text-3xl md:text-4xl font-bold md:leading-snug ">
                Privacy Policy
              </span>
            </div>
            <section className="w-full mx-auto  markdown-blog">
              <article>
                <p className="text-lg  leading-snug text-gray-700">
                  This Privacy Policy will help you better understand how we
                  collect, use, and share your personal information. If we
                  change our privacy practices, we may update this privacy
                  policy. If any changes are significant, we will let you know
                  (for example, through the Shopify admin or by email).
                </p>

                <h2>Our Value</h2>
                <p>
                  Trust is the foundation of the Shopify platform and includes
                  trusting us to do the right thing with your information. Three
                  main values guide us as we develop our products and services.
                  These values should help you better understand how we think
                  about your information and privacy.
                </p>

                <h2>Your information belongs to you</h2>
                <p>
                  We carefully analyze what types of information we need to
                  provide our services, and we try to limit the information we
                  collect to only what we really need. Where possible, we delete
                  or anonymize this information when we no longer need it. When
                  building and improving our products, our engineers work
                  closely with our privacy and security teams to build with
                  privacy in mind. In all of this work our guiding principle is
                  that your information belongs to you, and we aim to only use
                  your information to your benefit.
                </p>

                <h2>We protect your information from others</h2>
                <p>
                  If a third party requests your personal information, we will
                  refuse to share it unless you give us permission or we are
                  legally required. When we are legally required to share your
                  personal information, we will tell you in advance, unless we
                  are legally forbidden.
                </p>

                <h2>
                  We help merchants and partners meet their privacy obligations
                </h2>
                <p>
                  Many of the merchants and partners using Shopify do not have
                  the benefit of a dedicated privacy team, and it is important
                  to us to help them meet their privacy obligations. To do this,
                  we try to build our products and services so they can easily
                  be used in a privacy-friendly way. We also provide detailed
                  FAQs and documentation covering the most important privacy
                  topics, and respond to privacy-related questions we receive.
                </p>

                <h2>Why we process your information</h2>
                <p>
                  We generally process your information when we need to do so to
                  fulfill a contractual obligation (for example, to process your
                  subscription payments to use the Shopify platform), or where
                  we or someone we work with needs to use your personal
                  information for a reason related to their business (for
                  example, to provide you with a service). Laws in the European
                  Economic Area (“EEA”) and in the United Kingdom (“UK”) call
                  these reasons “legitimate interests.” These “legitimate
                  interests” include:
                </p>

                <h2>Where we send your information</h2>
                <p>
                  We are a Canadian company, but we work with and process data
                  about individuals across the world. To operate our business,
                  we may send your personal information outside of your state,
                  province, or country, including to the United States. This
                  data may be subject to the laws of the countries where we send
                  it. We take steps to protect your information when we send
                  your information across borders.
                </p>

                <p>
                  Depending on whether you are a merchant, customer, partner,
                  user or visitor, please refer to our supplemental privacy
                  policies, as relevant.
                </p>

                <h2>How we protect your information</h2>
                <p>
                  Our teams work tirelessly to protect your information, and to
                  ensure the security and integrity of our platform. We also
                  have independent auditors assess the security of our data
                  storage and systems that process financial information.
                  However, we all know that no method of transmission over the
                  Internet, and method of electronic storage, can be 100%
                  secure. This means we cannot guarantee the absolute security
                  of your personal information. You can find more information
                  about our security measures
                </p>
              </article>
            </section>
          </div>
        </div>
      </div>

      <Footer />
    </>
  );
}
